### PR TITLE
`VVPSDK.version` getter

### PR DESCRIPTION
**Pull request by AndriiMoskvin**
- [x] Release of version 1.1.0
- [x] `VVPSDK.version` getter added

### CODE REVIEW

**Comment by balavor** [comment]
screen shot 2019-01-10 at 15 22 15

Not so pretty as for me. I prefer how it used to be before.

**Comment by AndriiMoskvin** [comment]
@RomanTysiachnik I will try correct this.

**Comment by AndriiMoskvin** [comment]
@RomanTysiachnik RFR.

**Comment by AndriiMoskvin** [comment]
@RomanTysiachnik RFR.

**Review by balavor — APPROVED** [review]
Looks fine 👍

**Pull request merged**
