### PR TITLE
Tutorials + changelog update

### PR DESCRIPTION
**Pull request by AndriiMoskvin**
## Changes

- [x] Tutorials update
- [x] CHANGELOG.md update

@VerizonAdPlatforms/video-partner-sdk-developers: Please review.

### CODE REVIEW

**Review by balavor — APPROVED** [review]

**Review by balavor — DISMISSED** [review]
Rebase please

**Review by VladyslavAnokhin — DISMISSED** [review]

**Comment by RomanTysiachnik** [comment]
@AndriiMoskvin rebase please.

**Comment by balavor** [comment]
Please, wait for the next release.

**Comment by AndriiMoskvin** [comment]
@VladyslavAnokhin @RomanTysiachnik RFR.

**Review by VladyslavAnokhin — APPROVED** [review]

**Review by balavor — APPROVED** [review]

**Pull request merged**
