### PR TITLE
Added script to lint podspec only if necessary

### PR DESCRIPTION
**Pull request by balavor**
@VerizonAdPlatforms/video-partner-sdk-developers: Please review.

### CODE REVIEW

**Comment by balavor** [comment]
@AndriiMoskvin @VladyslavAnokhin RFR

**Review by AndriiMoskvin — DISMISSED** [review]
Should be in the build-scripts - consider creating ticket to improve this.

**Comment by balavor** [comment]
Done

**Review by AndriiMoskvin — DISMISSED** [review]
Still think this should be moved to the build scripts repo.

**Comment by VladyslavAnokhin** [comment]
`wip` - it's a bad comment message

**Comment by balavor** [comment]
It is still `wip` because that script is not working in fastlane

**Comment by AndriiMoskvin** [comment]
Still not working?

**Review by AndriiMoskvin — APPROVED** [review]

**Pull request merged**
