### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MarkGerl**
## Changes
Softened the Swift Package Manager "unsupported" language, and made it pinkish vs red.

@OathAdPlatforms/mobile-sdk-developers: Please review.

### CODE REVIEW

**Review by balavor — DISMISSED** [review]
Great job 👍 
Are you going to update [tutorials](https://github.com/VerizonAdPlatforms/VerizonVideoPartnerSDK-iOS/tree/master/OathVideoPartnerSDK-Tutorials)?

**Comment by AndriiMoskvin** [comment]
@BenLloydPearson Could you please enable check to require up-to-date merge for `master` protected branch?

Also ideally I would like to see those checks enabled for following repos:
https://github.com/VerizonAdPlatforms/OneMobileSDK-videorenderer-ios
https://github.com/VerizonAdPlatforms/OneMobileSDK-build-scripts-ios
https://github.com/VerizonAdPlatforms/OneMobileSDK-controls-ios
https://github.com/VerizonAdPlatforms/VerizonVideoPartnerSDK-PlayerCore-iOS

**Comment by BenLloydPearson** [comment]
@AndriiMoskvin, that configuration is already enabled for all of those repos. However, I noticed they don't require Travis CI to pass before merging. Is that the configuration you want enabled?

**Comment by MarkGerl** [comment]
Temporarily using this to upload Android images:

controls-portrait
controls-landscape

**Comment by MarkGerl** [comment]
show-hide-controls 1
port
land

**Review by AndriiMoskvin — APPROVED** [review]

**Comment by AndriiMoskvin** [comment]
@BenLloydPearson You are right - definitely Travis have to be required check.
Current branch is not on top of master but still can be merged - but probably it is ok if it has no conflicts.

Ideally I want to have following picture on protected branch for each of the repos I've mentioned:
screen shot 2019-01-03 at 8 39 09 pm

Replace Screwdrive with any other Travis - and that is it!

**Comment by BenLloydPearson** [comment]
OK, Travis CI passing is now required for merging on all of these repos.

**Pull request merged**
